travis:
  secure:
    BINSTAR_TOKEN: DTpWpWQUB8UtXfSo1h7SW5wFa7dBVedHPidARObgYe/cdee8tjQdflo9sY6YyZYqV/s/aBEHIpXOH99gWgbVLv+Qouf5Jr9k7oLWfij4YBOF3siqzV55f8AuXp1nB7yY1ByUbuiWM+iwHCermGyHmgJg5EyHh5zDHN9rpIjYTPNbGU5kTgYVA9qgx/LPWeByPA8zx1dM3yVEZ1Ft2Mm856iIz0ytcgrhHl2Tm8LES3oDI1B+tKWRXpN6T6ZpMcJH6YqIVAKRdsBecwzF/xBldn8kke/Y4o9guI/lr2L5JQ+by1NsTQRDxPj6nudLKB9iQQkpfPXZeKrILsT9gRXj/3ILv70D3uAuQt9h2qEUSiOsqF+NY/ceW1uuO9PGQNyPX29sF+TIPZ+uzeQwdpv3kbf3VZYc1pQDxcYItDe7/g3sMIIF49RQy+FAijQqGUHQqe5inIl26l1CJtwcu2iVL95ZDxJmSIQols6Zd55ACdKvE77elP6wrqKZUUqBj6if+3Molp8vJqBQc6IWXRsS+m2pfwASqKV6Nesrc05V49uU5xlPgaPspkqBYRlLVrnSpGmk/beejrMF19jQKQz2t4RvOtaspHdZ8XUCewZLKzUPBVjeJEBZBjTI6YJCtb4bs9w3KkbNtLRD/8nL2hBCtDtqkFaDO/zr7NOkli1Qd94=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
