travis:
  secure:
    BINSTAR_TOKEN: HPatYvGnjCdl7RZZFY/EUc99D+0lDQUhFUk7ASr5X7gXawN9QmcACT+3ylGL4a/i9Ru+k42VWqyORwVCIGSBwTT4vzOnBSjxj8TRRf6U83x/QwXRkXBbDq7a2lntWMzx8XMyJ6gUOz6rZxSS1cFy9uII1Z4luzW3Uc/k0D6gXg7oBycegjwV1iYnv/Pac1hIeBozNTAFOuhSeSgqYmdHqXNvqV/OhW9oVFWbPvHOofpN53AHiZDS+4gTHszLtBzhrb5ozkq4CYHCF0sM/nxeON69kgFblNTVlNap6Fx+27yqXusnyPhounH0lg1RCOGDRtnmZjM0U3RNZpZTuNYgND3dpRlrHKMtcwZeHnhzFdm/nsrYNWFEvxFAPajHjwIHaXGRD9oSTr1LCU5mNej+eWz4PevaJt8m3lvBoiG6WXjegVUeMQG6fQUXU9HVTM7PovD7AftSRuRZBOtl4/ItsPOA717cbI5vW29siwpnMNQ9OoU2SWuV4Yh9XfRdZKqDxUYBT7m3NMuhMjxhGu0jrjQVKXi76ROj3gOma2iXkKCsDIu1lL1BsynuxOu0FWiEdk23PdAWcGeqQjBJHMYLn1m/rpRONtbqeqj5vRfQYciePpfrzEbv6ETqYoUH476O7jrK4RRaIAAoKgYNr8u26AIWxEfR1ARqjO9UBUd3vjY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
